### ISSUE TITLE
能否出个简单的视频教程

### ISSUE THREAD

**Issue by 531830894** [tencentyun/iotexplorer-h5-panel-demo#14]
对于你们来说应该一会就弄完了，对有搞硬件的来说 看这些东西简直是天书啊。可以吗？

**Comment by xiaoyuze88** [comment]
视频教程正在制作，下个月可以看到

**Comment by noonhorse** [comment]
> 对于你们来说应该一会就弄完了，对有搞硬件的来说 看这些东西简直是天书啊。可以吗？
这里有在线视频
https://cloud.tencent.com/developer/salon/live-1688
