### ISSUE TITLE
说句实话，我一个前端工程师看到你这个文档都一脸懵逼，能否写多点内容

### ISSUE THREAD

**Issue by lw1995** [tencentyun/iotexplorer-h5-panel-demo#15]
说句实话，我一个前端工程师看到你这个文档都一脸懵逼，能否写多点内容

**Comment by xuhongv** [comment]
参考下我写的这文章：https://xuhong.blog.csdn.net/article/details/120282326

**Comment by xiaoyuze88** [comment]
README只是该Demo的文档，关于h5面板详细流程及文档可以参考官网文档 https://cloud.tencent.com/document/product/1081/49028
