### ISSUE TITLE
如何在H5页面中调用设备离线状态的弹出窗口

### ISSUE THREAD

**Issue by Michalhu** [tencentyun/iotexplorer-h5-panel-demo#2]
我想在H5页面中做这样的功能，当设备离线时，能够有个接口给我调用如下离线提醒弹窗，该如何调用？
![offline_pop](https://user-images.githubusercontent.com/38523038/80183473-79084900-863b-11ea-9cbf-d8648e48515c.png)

**Comment by xyh569923911** [comment]
请问一下，这个h5页面怎么写

**Comment by imgss** [comment]
可以使用[设备离线组件]( https://cloud.tencent.com/document/product/1081/67449#.E8.AE.BE.E5.A4.87.E7.A6.BB.E7.BA.BF.E6.8F.90.E7.A4.BA.E7.BB.84.E4.BB.B6)
