### ISSUE TITLE
有接入react native的吗？

### ISSUE THREAD

**Issue by Raysonly** [tencentyun/iotexplorer-h5-panel-demo#21]
有接入react native的吗？我导入就报错

ERROR in ./node_modules/react-native/index.js 14:7
Module parse failed: Unexpected token (14:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
| // Components
> import typeof AccessibilityInfo from './Libraries/Components/AccessibilityInfo/AccessibilityInfo';
| import typeof ActivityIndicator from './Libraries/Components/ActivityIndicator/ActivityIndicator';
| import typeof Button from './Libraries/Components/Button';
 @ ./src/DevicePanel/DevicePanel.jsx 12:0-81
 @ ./src/DevicePanel/index.js
 @ ./src/app.jsx

**Comment by imgss** [comment]
暂不支持 react native，可以考虑WebView作为替代方案
