### ISSUE TITLE
代码方面的资料太少了,新手看不懂,百毒也查不到,准备放弃了

### ISSUE THREAD

**Issue by hmuyin** [tencentyun/iotexplorer-h5-panel-demo#26]
代码方面的资料太少了,新手看不懂,百毒也查不到,准备放弃了

**Comment by imgss** [comment]
对于新手有以下建议：
- 看官方文档： https://cloud.tencent.com/document/product/1081/67441
- 看入门课程视频： https://cloud.tencent.com/developer/salon/live-1688
- 遇到问题还可以提工单，我们会有同事为大家答疑解惑的～

**Comment by hmuyin** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。
