### ISSUE TITLE
如何调用设备设置菜单并自定义设备的详细菜单

### ISSUE THREAD

**Issue by Michalhu** [tencentyun/iotexplorer-h5-panel-demo#3]
目前腾讯连连提供了通用的设备设置菜单，如下图。请问在H5页面中如何调用该菜单显示，并且能够提供一些接口便于设备厂商增加一些个性化的菜单，请问该如何做？

![device_setup](https://user-images.githubusercontent.com/38523038/80183938-50cd1a00-863c-11ea-9966-7855228552ce.jpg)

**Comment by zhebanzhongzhong** [comment]
查看[qcloud-iotexplorer-h5-panel-sdk](https://www.npmjs.com/package/qcloud-iotexplorer-h5-panel-sdk)的文档
sdk.goDeviceDetailPage
跳转到腾讯连连通用的产品详情页（小程序页面）

**Comment by imgss** [comment]
可以使用 [H5 自定义设备详情视图](https://cloud.tencent.com/document/product/1081/67449#h5-.E8.87.AA.E5.AE.9A.E4.B9.89.E8.AE.BE.E5.A4.87.E8.AF.A6.E6.83.85.E8.A7.86.E5.9B.BE),支持添加个性化菜单
