### ISSUE TITLE
文档好像说的不够详细，能否说的更又条理一些？？

### ISSUE THREAD

**Issue by atonesapple** [tencentyun/iotexplorer-h5-panel-demo#9]
怎么开发品牌的小程序，还有怎么开发配网的页面，已经后续的操作，都是个问题

**Comment by xuhongv** [comment]
参考下我写的这文章：https://xuhong.blog.csdn.net/article/details/120282326

**Comment by xiaoyuze88** [comment]
README只是该Demo的文档，关于h5面板详细流程及文档可以参考官网文档 https://cloud.tencent.com/document/product/1081/49028

**Comment by atonesapple** [comment]
收到，谢谢！










在 2021-09-15 09:12:29，"半颗心脏 | 徐宏" ***@***.***> 写道：

参考下我写的这文章：https://xuhong.blog.csdn.net/article/details/120282326

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
